### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by Beaneater911** [CleanFlash/installer#1]
System.UnauthorizedAccessException: Access to the path 'activex.vch' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at CleanFlashCommon.FileUtil.DeleteFile(FileInfo file)
   at CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   at CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   at CleanFlashCommon.Uninstaller.DeleteFlashPlayer()
   at CleanFlashInstaller.InstallForm.<>c__DisplayClass13_0.<BeginInstall>b__0()

**Comment by darktohka** [comment]
Hello!

1. Are you running the installer as an administrator?
2. Do you have an admin account or a regular user account in Windows?
3. What OS are you using? (example: Windows 10.0.19043.985 64-bit)
4. Do you have any browsers open or anything that might use Flash? (for example: Internet Explorer or Newgrounds Player)
5. Head to "C:\Windows\System32\Macromed\Flash" and right click on "Properties" for "activex.vch". Is the file marked as "read-only"? Can you delete the file yourself? If not, please make a screenshot of the Advanced Security tab, for example:
![image](https://user-images.githubusercontent.com/16326697/119256022-4676aa00-bbc7-11eb-8c40-ef5b1ddc647d.png)

**Comment by Thehelper104** [comment]
![image](https://user-images.githubusercontent.com/38369997/119810302-24b94380-bea3-11eb-9f48-6eabd892488e.png)
i think i figured out his issue.

**Comment by Thehelper104** [comment]
or her issue, idk

**Comment by imagina** [comment]
same error here...

**Comment by Xacto18** [comment]
Check #5 for the workaround that I posted, see if it helps.

**Comment by darktohka** [comment]
Hey, please try the latest version: 34.0.0.164 at https://github.com/CleanFlash/installer/releases/latest. Let me know if it fixes your issue!

**Comment by zhm86** [comment]
The latest version does not fix it, use https://github.com/jschicht/RunAsTI to run the installer with TrustedInstaller privilege to solve the problem.

**Comment by r3sus** [comment]
Should be solved now. Please confirm.
