### ISSUE TITLE
any fix for this?

### ISSUE THREAD

**Issue by Wanderist237** [CleanFlash/installer#10]
i got this error
CleanFlashCommon.InstallException: Failed to apply changes to registry: error code 1

ERROR: Error accessing the registry.
   at CleanFlashCommon.RegistryManager.ApplyRegistry(String registryContents)
   at CleanFlashInstaller.Installer.Install(IProgressForm form, InstallFlags flags)
   at CleanFlashInstaller.InstallForm.<>c__DisplayClass13_0.<BeginInstall>b__0()

**Comment by Wanderist237** [comment]
nvm
