### ISSUE TITLE
Flash Center removal issue

### ISSUE THREAD

**Issue by Diicorp95** [CleanFlash/installer#14]
I received this message when the uninstaller was deleting _Flash Center_ (I don't have it!).
Seems like it doesn't related to _Clean Flash_ and uninstaller works, because _Revo Uninstaller_ didn't find any residual files.

Translated from Russian language:
```
System.IO.IOException: The process cannot access the file "launcher.ini" because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at CleanFlashCommon.FileUtil.DeleteFile(FileInfo file)
   at CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   at CleanFlashCommon.FileUtil.WipeFolder(String baseDir)
   at CleanFlashCommon.Uninstaller.DeleteFlashCenter()
   at CleanFlashCommon.Uninstaller.Uninstall(IProgressForm form)
   at CleanFlashUninstaller.UninstallForm.<BeginInstall>b__7_0()
```

**Windows NT 6.1 x64**

**Comment by EMJzero** [comment]
A simple fix that worked for me was to close ALL browser instances, and that included other programs that are built upon browser engines, Discord in an example! Close all those programs and the installation should be fine!

**Comment by Diicorp95** [comment]
I don't have such resource-consuming clients as Discord.

Anyway, as I said before, it's uninstalled normally. Except that mentioned Flash Center never existed in my system.
