### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by imageny** [CleanFlash/installer#2]
The installation for PPAPI and NPAPI works fine, however when I tried it with the OCX, this happened:

CleanFlashCommon.InstallException: Failed to apply changes to registry: error code 1

ERROR: Error accessing the registry.
   at CleanFlashCommon.RegistryManager.ApplyRegistry(String registryContents)
   at CleanFlashInstaller.Installer.Install(IProgressForm form, InstallFlags flags)
   at CleanFlashInstaller.InstallForm.<>c__DisplayClass13_0.<BeginInstall>b__0()

And before you ask, yes, I ran it as admin.

**Comment by darktohka** [comment]
Thank you for pinpointing the cause of the issue.

Would you kindly try this new test version of the installer? (GitHub doesn't let users upload large ZIP files apparently)

https://www110.zippyshare.com/v/yd0GBzIZ/file.html

Thank you! Let me know if it works.

**Comment by imageny** [comment]
CleanFlashCommon.InstallException: Failed to apply changes to registry: error code 1

ERROR: Error accessing the registry.
   at CleanFlashCommon.RegistryManager.ApplyRegistry(String registryContents)
   at CleanFlashInstaller.Installer.Install(IProgressForm form, InstallFlags flags)
   at CleanFlashInstaller.InstallForm.<>c__DisplayClass13_0.<BeginInstall>b__0()

Same error

**Comment by Xacto18** [comment]
Check #5 for the workaround that I posted, see if it helps.

**Comment by darktohka** [comment]
Hey, please try the latest version: 34.0.0.164 at https://github.com/CleanFlash/installer/releases/latest. Let me know if it fixes your issue!
