### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by JohanBLU** [CleanFlash/installer#20]
i selected both npapi and activex and i got this error.

CleanFlashCommon.InstallException: Failed to register ActiveX plugin: error code -1073740940

   at CleanFlashInstaller.Installer.RegisterActiveX(String filename)
   at CleanFlashInstaller.Installer.Install(IProgressForm form, InstallFlags flags)
   at CleanFlashInstaller.InstallForm.<>c__DisplayClass13_0.<BeginInstall>b__0()

**Comment by JohanBLU** [comment]
I just installed it during RunInTS and it worked. however now when I try and go to a website with flash it keeps bugging me if i wanna enable flash or not. and when i click yes it does nothing but ask again. I'm using IE11 and Windows 7 for this
