### ISSUE TITLE
Instalation error with non english windows xp

### ISSUE THREAD

**Issue by Solarwuff** [CleanFlash/installer#26]
i am getting the following install error massage when i try to install CleanFlash 34.0.0.184 on Windows XP Home SP3 Dutch 
The installer worked fine on a english version of the same OS

System.ComponentModel.Win32Exception (0x80004005): Het systeem kan het opgegeven bestand niet vinden (The system cannot find the specified file)
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CleanFlashCommon.ProcessRunner.RunUnmanagedProcess(ProcessStartInfo startInfo)
   at CleanFlashCommon.Uninstaller.DeleteTask(String task)
   at CleanFlashCommon.Uninstaller.Uninstall(IProgressForm form)
   at CleanFlashInstaller.InstallForm.<>c__DisplayClass15_0.<BeginInstall>b__0()

**Comment by r3sus** [comment]
Can you please check after which installation step (i.e. installing Firefox plugin) is the error encountered? 

Also please check if those directories exist: 
`C:\Windows\System32\Macromed\Flash`
`C:\Windows\SysWOW64\Macromed\Flash`

As alternative, try semi-manual installation: https://github.com/darktohka/FlashPatch
