### ISSUE TITLE
why clean flash player is not working?

### ISSUE THREAD

**Issue by deividbinev12** [CleanFlash/installer#28]
System.UnauthorizedAccessException: Access to the path 'Flash8.ocx' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at CleanFlashCommon.FileUtil.DeleteFile(FileInfo file)
   at CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   at CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   at CleanFlashCommon.Uninstaller.DeleteFlashPlayer()
   at CleanFlashInstaller.InstallForm.<>c__DisplayClass15_0.<BeginInstall>b__0()

**Comment by r3sus** [comment]
Try `Run as administrator`.
