### ISSUE TITLE
Please fix these errors.

### ISSUE THREAD

**Issue by joeynigro** [CleanFlash/installer#7]
CleanFlashCommon.InstallException: Failed to apply changes to registry: error code 1

ERROR: Error accessing the registry.
   at CleanFlashCommon.RegistryManager.ApplyRegistry(String registryContents)
   at CleanFlashInstaller.Installer.Install(IProgressForm form, InstallFlags flags)
   at CleanFlashInstaller.InstallForm.<>c__DisplayClass13_0.<BeginInstall>b__0()

**Comment by darktohka** [comment]
Hey, please try the latest version: 34.0.0.164 at https://github.com/CleanFlash/installer/releases/latest. Let me know if it fixes your issue!

**Comment by Thehelper104** [comment]
that wont fix it. CleanFlashCommon.InstallException: Failed to apply changes to registry: error code 1

ERROR: Error accessing the registry.
   at CleanFlashCommon.RegistryManager.ApplyRegistry(String registryContents)
   at CleanFlashInstaller.Installer.Install(IProgressForm form, InstallFlags flags)
   at CleanFlashInstaller.InstallForm.<>c__DisplayClass13_0.<BeginInsta

**Comment by r3sus** [comment]
happens when installing 
ActiveX (OCX)
(IE/Embedded/Desktop)
else works fine
(does installer uses ActiveX?)

**Comment by r3sus** [comment]
New version installs and works just fine, thanks a lot! Tested on IE, Basilisk, Waterfox.
